### ISSUE TITLE
Not able to expose service

### ISSUE THREAD

**Issue by gustavosr98** [canonical/mysql-operator#53] opened 2022-10-11 21:00 UTC
### Bug Description

I am not able to expose Mysql service outside of private network
I believe the issue is on the open ports Juju shows in status

### To Reproduce

```bash
$ juju add-credential aws --client
$ juju show-cloud --local aws
$ juju bootstrap aws aws-controller

$ juju add-model databases
$ juju deploy mysql --channel=latest/edge
$ juju expose mysql

$ telnet 54.145.214.34 3306             
Trying 54.145.214.34...
telnet: Unable to connect to remote host: Connection timed out 
```

### Environment

Cloud: AWS
Juju: 2.9.34 (Client and Controller)
Mysql charm: latest/edge (rev 80)

```
$ juju status -m aws-controller:databases
Model      Controller      Cloud/Region   Version  SLA          Timestamp
databases  aws-controller  aws/us-east-1  2.9.34   unsupported  16:49:50-04:00

App    Version          Status  Scale  Charm  Channel      Rev  Exposed  Message
mysql  8.0.30-0ubun...  active      1  mysql  latest/edge   80  yes      Unit is ready: Mode: RW

Unit      Workload  Agent  Machine  Public address  Ports  Message
mysql/0*  active    idle   0        54.145.214.34          Unit is ready: Mode: RW

Machine  State    Address        Inst id              Series  AZ          Message
0        started  54.145.214.34  i-031aae0b28befda3f  focal   us-east-1c  running
```

### Relevant log output

```shell
n/a
```

### Additional context

As a workaround I had to open the service port manually
```bash
$ juju run -m aws-controller:databases -u mysql/leader 'open-port 3306/tcp'
$ juju status -m aws-controller:databases

databases  aws-controller  aws/us-east-1  2.9.34   unsupported  16:53:22-04:00

App    Version          Status  Scale  Charm  Channel      Rev  Exposed  Message
mysql  8.0.30-0ubun...  active      1  mysql  latest/edge   80  yes      Unit is ready: Mode: RW

Unit      Workload  Agent  Machine  Public address  Ports     Message
mysql/0*  active    idle   0        54.145.214.34   **3306/tcp**  Unit is ready: Mode: RW

Machine  State    Address        Inst id              Series  AZ          Message
0        started  54.145.214.34  i-031aae0b28befda3f  focal   us-east-1c  running

$ telnet 54.145.214.34 3306
Trying 54.145.214.34...
Connected to 54.145.214.34.
Escape character is '^]'.
[
8.0.30-0ubuntu0.20.04.2'=KjZ2�,=z%J(2
caching_sha2_password^]
telnet> quit
Connection closed.
```

After doing so, I do was able to see AWS security groups getting created

Name | Security group rule ID | IP version | Type | Protocol | Port range | Source | Description
--- | --- | --- | --- | --- | --- | --- | --- 
– | sgr-055ed97fc945cee9a | IPv6 | MYSQL/Aurora | TCP | 3306 | ::/0 | –
– | sgr-040da8c492cfa9a3e | IPv4 | MYSQL/Aurora | TCP | 3306 | 0.0.0.0/0 | –

**Comment by taurus-forever** [comment] 2023-02-02 09:37
Hi @gustavosr98 and thank you for the bugreport!

The lack of exposing port is confirmed and will be addressed in https://warthogs.atlassian.net/browse/DPE-1214, https://warthogs.atlassian.net/browse/DPE-1215, https://warthogs.atlassian.net/browse/DPE-1216 and https://warthogs.atlassian.net/browse/DPE-1216 for mysql/mysql-router*VM/K8s respectively.

Tnx!

**Comment by taurus-forever** [comment] 2023-03-21 21:45
Dear @gustavosr98 the latest versions of VM charms `mysql` (channel edge) and `mysql-router` (channel dpe/edge) are able to expose ports, please check it from your side. K8s versions of charms are pending for migration on juju 3.1 (there are recent changes about sidecar ports exposing). 

I am resolving this ticket as it was about VM charm. Feel free to reopen in if the issue is still reproducible on your side.
Thank you for the bugreport!

**Closed by taurus-forever** 2023-03-21 21:45 UTC
Labels: bug
